# Use root/example as user/password credentials
# Connect: mysql -u root -h 127.0.0.7 -p
# Or open localhost:8080 for phpmyadmin ui
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080