global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: jobs
    metrics_path: /metrics
    # Must set for pushgateway
    honor_labels: true
    static_configs:
      - targets:
          - 'prometheus-pushgateway:9091'
  - job_name: jobrunner
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8010'

        
      
